export const minersMock = [
  {
    id: 1,
    name: "Bitmain Antminer L7 (9.5Gh)",
    image: "/my-miners/miner-1.png",
    status: "Active",
    power: "20 W/TH",
    hashrate: "12.5 TH/s",
  },
  {
    id: 2,
    name: "Bitmain Antminer L9 (16Gh)",
    image: "/my-miners/miner-2.png",
    status: "Active",
    power: "21 W/TH",
    hashrate: "11.5 TH/s",
  },
  {
    id: 3,
    name: "Bitmain Antminer KS5 Pro (21Th)",
    image: "/my-miners/miner-3.png",
    status: "Active",
    power: "20 W/TH",
    hashrate: "18 TH/s",
  },
  {
    id: 4,
    name: "Bitmain Antminer KS5 (20Th)",
    image: "/my-miners/miner-3.png",
    status: "Active",
    power: "20 W/TH",
    hashrate: "18 TH/s",
  },
  {
    id: 5,
    name: "DragonBall Miner A40",
    image: "/my-miners/miner-2.png",
    status: "Warning",
    power: "20 W/TH",
    hashrate: "18 TH/s",
  },
  {
    id: 6,
    name: "DragonBall Miner A11",
    image: "/my-miners/miner-1.png",
    status: "Inactive",
    power: "20 W/TH",
    hashrate: "18 TH/s",
  },
];
